"use client";

import { useRouter } from "next/navigation";

export default function TermsPage() {
  const router = useRouter();

  return (
    <div className="flex-1 flex flex-col min-h-0">
      <header className="bg-surface border-b border-subtle/50 shadow-sm shadow-black/5 sticky top-0 z-40">
        <div className="relative flex items-center justify-center w-full px-6 py-4">
          <button
            aria-label="Go back"
            onClick={() => router.back()}
            className="absolute left-4 hover:bg-stone-100 dark:hover:bg-stone-800 p-2 rounded-full transition-all duration-300 flex items-center justify-center btn-press"
          >
            <span className="material-symbols-outlined text-rose">arrow_back</span>
          </button>
          <h1 className="text-2xl font-serif font-bold text-primary tracking-tight not-italic">
            Terms of Service
          </h1>
        </div>
      </header>

      <main className="flex-1 w-full max-w-2xl mx-auto px-6 py-8 pb-32 overflow-y-auto">
        <div className="prose prose-stone dark:prose-invert prose-sm max-w-none space-y-8">
          <p className="text-secondary text-sm leading-relaxed">
            <span className="font-bold text-primary">Last Updated:</span> May 2026
          </p>

          <section className="space-y-3">
            <h2 className="font-serif text-lg text-primary">1. Acceptance of Terms</h2>
            <p className="text-secondary text-sm leading-relaxed">
              By accessing or using Moms &amp; Pops (&ldquo;the Service&rdquo;), you agree to be
              bound by these Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-serif text-lg text-primary">2. Description of Service</h2>
            <p className="text-secondary text-sm leading-relaxed">
              Moms &amp; Pops provides an AI-powered platform that allows users to create digital
              personas (&ldquo;Heirlooms&rdquo;) based on uploaded memories, text conversations, and
              voice recordings. These personas are generated using machine learning models and are
              intended for personal, commemorative use.
            </p>
            <p className="text-secondary text-sm leading-relaxed">
              <span className="font-bold text-primary">Important:</span> The Service is in early
              access / beta. Features, availability, and performance are not guaranteed and depend
              on the success of our launch, infrastructure scaling, and model training.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-serif text-lg text-primary">3. User Accounts</h2>
            <p className="text-secondary text-sm leading-relaxed">
              You must provide accurate information when creating an account. You are responsible
              for maintaining the confidentiality of your login credentials and for all activity
              under your account. You must be at least 13 years old to use the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-serif text-lg text-primary">4. Content You Upload</h2>
            <p className="text-secondary text-sm leading-relaxed">
              You retain ownership of all text, images, audio, and other content you upload to the
              Service (&ldquo;User Content&rdquo;). By uploading User Content, you grant us a
              limited license to process, analyze, and store it solely for the purpose of providing
              the Service to you. We do not use your User Content to train our models unless you
              explicitly opt in.
            </p>
            <p className="text-secondary text-sm leading-relaxed">
              You represent that you have the right to upload any content you provide and that it
              does not violate any third-party rights or applicable laws.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-serif text-lg text-primary">5. AI-Generated Content</h2>
            <p className="text-secondary text-sm leading-relaxed">
              Persona responses are generated by artificial intelligence and may not always be
              accurate, appropriate, or reflective of the actual person they represent. You
              acknowledge that AI-generated content carries inherent risks and agree to use the
              Service with this understanding. We are not responsible for the specific content of
              AI-generated responses.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-serif text-lg text-primary">6. Subscriptions &amp; Payment</h2>
            <p className="text-secondary text-sm leading-relaxed">
              Paid tiers are billed monthly. Prices are subject to change with 30 days notice.
              Refunds are handled on a case-by-case basis. You may cancel at any time; cancellation
              takes effect at the end of the current billing period.
            </p>
            <p className="text-secondary text-sm leading-relaxed">
              <span className="font-bold text-primary">Beta pricing:</span> Current prices reflect
              our pre-scale phase and will increase as the Service matures. Early subscribers may
              receive grandfathered pricing at our discretion.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-serif text-lg text-primary">7. Acceptable Use</h2>
            <p className="text-secondary text-sm leading-relaxed">
              You agree not to use the Service to create personas that impersonate living persons
              without their consent, generate harmful or illegal content, harass or defame others,
              or violate any applicable laws. We reserve the right to suspend or terminate accounts
              that violate these terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-serif text-lg text-primary">8. Limitation of Liability</h2>
            <p className="text-secondary text-sm leading-relaxed">
              The Service is provided &ldquo;as is&rdquo; without warranties of any kind. We are not
              liable for any damages arising from your use of the Service, including emotional
              distress related to AI-generated persona content. Our total liability is limited to
              the amount you paid us in the 12 months preceding the claim.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-serif text-lg text-primary">9. Termination</h2>
            <p className="text-secondary text-sm leading-relaxed">
              You may delete your account and all associated data at any time through the Settings
              page. We may terminate or suspend your account for violations of these terms. Upon
              termination, your User Content and personas will be permanently deleted.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-serif text-lg text-primary">10. Changes to Terms</h2>
            <p className="text-secondary text-sm leading-relaxed">
              We may update these terms from time to time. Material changes will be communicated
              via email or in-app notification. Continued use after changes constitutes acceptance.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-serif text-lg text-primary">11. Contact</h2>
            <p className="text-secondary text-sm leading-relaxed">
              For questions about these terms, contact us at{" "}
              <span className="text-rose">legal@momspops.app</span>.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
